### ISSUE TITLE
Incompatible with Gradle 8.0.0+

### ISSUE THREAD

**Issue by Lordfirespeed** [Strumenta/antlr-kotlin#100]
Due to the legacy IncrementalTaskInputs API being [removed](https://docs.gradle.org/current/userguide/upgrading_version_7.html#legacy_incrementaltaskinputs_api) in Gradle 8, this plugin does not work with gradle 8 and above.

**Comment by atsushieno** [comment]
I kinda needed to upgrade Gradle to 8.0 and antlr-kotlin Gradle plugin was the bottleneck. I created a fix for my own fork. I'm not sure what the Gradle migration plan at here though. Feel free to take it anyways.
https://github.com/atsushieno/antlr-kotlin/commit/d64121e57be8a815aa1a2b3e9e37f1176e4b4b7f

**Comment by atsushieno** [comment]
Actually why not just create a PR - discard it if the dev. team want to do otherwise.

**Comment by Lordfirespeed** [comment]
Thankyou! ♥️♥️
