### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/antlr-kotlin#109]

**Comment by lppedd** [comment]
Before publishing, do we want to change package names?

Currently the runtime lives under `org.antlr.v4.kotlinruntime`, which is totally fine, however, what about moving to `org.antlr.v4.runtime` to align with Java?  
The benefit would be an easy switch from the Java world, as the only thing you'd have to do would be convert your custom listeners/visitors to Kotlin (e.g., using the IDE converter).

**Comment by lppedd** [comment]
Makes sense! Then forget about it.
