### ISSUE TITLE
Releasing ANTLR Kotlin _also_ under the BSD-3 clause

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/antlr-kotlin#144]
Dear @lppedd @drieks @phyrian @exaV @OldWartHog @brianguertin @atsushieno @tianyu @tim-patterson @alchitry @oleg-zinovev @ianparkinson @garyttierney @frett @wilkomanger @unosviluppatore

I am writing about your contributions to ANTLR Kotlin. A project that I originally started in 2017 and that benefitted from your help.

ANTLR Kotlin is released under the Apache License 2. 

However a team designing ANTLR 5 is considering including components of ANTLR Kotlin in their project. It could end up being used only for experiments, or, as I hope, became the basis of ANTLR 5. The reason for this choice is that the ANTLR Kotlin runtime can be compiled to WASM.

I think it would be an amazing possibility to contribute to the new generation of ANTLR and make our work more valuable. For that the team behind ANTLR 5 requested if you would consider granting the license to your work _also_ under the BSD-3 license. The differences between the two licenses seem minimal to me. What I am proposing is one of these alternatives.

So I am studying how to satisfy this request, while letting users of ANTLR Kotlin keep using future releases of ANTLR Kotlin under the Apache License 2, if they wish to do so. So there would be no changes for them.

Based on your answers there are three possible scenarios:

# Scenario 1: ANTLR Kotlin under both licenses

If we get the approval from all the authors (or the authors of 99%+ of the commits) then we will:
- Provide future versions of ANTLR Kotlin under both the Apache License 2 and the BSD-3 License. The users will decide which one they want to apply
- The ANTLR 5 team could use ANTLR Kotlin and benefits from future fixes
- Remove from the repository the contributions of the authors who do not agree to releasing their work _also_ under the BSD-3 License

# Scenario 2: ANTLR Kotlin as-is, plus "revisited fork"

If we get the approval from most of the authors (or the authors of 95%+ of the commits) then we will:
- Let the ANTLR Kotlin repository unchanged and provide _only_ after the Apache License 2, as it is the case now
- We will create a fork version of ANTLR Kotlin and remove from it the contributions of the authors who do not agree to releasing their work _also_ under the BSD-3 License. This fork will be _only_ under the BSD-3 license
- The ANTLR 5 team could use the forked version of ANTLR Kotlin

# Scenario 3: We do not proceed

If we do not the approval from most of the authors then we will drop this possibility:
- The ANTLR Kotlin repository will provide as it is now
- The ANTLR 5 team will rewrite the runtime on their own, without reusing any code from the ANTLR Kotlin project

---

# What do I need from you?

To answer this issue stating that you grant me the possibility to release your contributions to ANTLR Kotlin _also_ under the BSD-3 License, or alternatively to send me an email about that.

I am sorry to disturb you with this boring discussion about licenses and I am thankful for your contributions to the ANTLR Kotlin project. It has been providing value to different adopters during these years, and the fact we have the possibility to provide even more value is a great thing that you made possible.

Cheers,
Federico

**Comment by ftomassetti** [comment]
I have also reached some of you by email, if you had your emails available on GitHub

**Comment by garyttierney** [comment]
OK from me to license any contributions I've made under BSD-3.

**Comment by OldWartHog** [comment]
Federico,

I hereby grant you permission to release any contributions I have made  under the terms of either the Apache2 or BSD-3 licence

And I’m really happy to see the project grow, so well done in creating and maintaining this project.

Martin

**Comment by ianparkinson** [comment]
That's really exciting!

I'm happy for my trivial contribution to antlr-kotlin to be released under
BSD-3.

**Comment by ftomassetti** [comment]
Thank you @garyttierney @ianparkinson and @OldWartHog 
I also got permission by @unosviluppatore and @lppedd by email

**Comment by drieks** [comment]
Hi,
its also fine for me to use both licenses!

**Comment by atsushieno** [comment]
I happily relicense my contributions under the BSD-3 license too (replied in the email too).

**Comment by oleg-zinovev** [comment]
Hi.
OK from me to license my contribution under BSD-3.

**Comment by exaV** [comment]
Hey, thanks for reaching out. Great to see the project grow! You may licence my contributions under BSD-3 as well.

**Comment by tianyu** [comment]
Yes! Please use my work on this project under the BSD-3 license!

**Comment by phyrian** [comment]
Sure, feel free to use my contributions under BSD-3 as well.

**Comment by ftomassetti** [comment]
Thank you all, I appreciate it!

At this point we got permissions from the contributors of 414 commits out of 425 (97.41%).
Let's see if we can get the permissions from the remaining 5 contributors.

**Comment by ericvergnaud** [comment]
Gents, as the lead of the antlr5 project, I thank you all for your rapid approval.
The antlr5-specs repo will soon go public, and the antlr5 code repo will be created soon after that.
You are more than welcome to contribute.
Since we're opting for a mono-repo, originally forked from the antrl4 repo, it might impact how we integrate the ANTLR Kotlin code base. Let me know if you have ideas on how to make this work in the best interest of everybody.
Also, and very importantly, since antlr5 will require WasmGC, which is currently only available in V8 (chrome, deno and node in a few months) ANTLR Kotlin will not be replaced any time soon. So I encourage you to continue investing in it, and to help figure out how to ensure these contributions make it to antlr5.

**Comment by lppedd** [comment]
> it might impact how we integrate the ANTLR Kotlin code base. Let me know if you have ideas on how to make this work in the best interest of everybody

Thanks! Happy to contribute changes/suggestions for the build system.  
I'll wait for the ANTLR5 spec repo to go public and then have a look at it.

We'll continue improving the multiplaform support, especially around JS/Wasm/WASI support, as soon as ideas come up.  
Ideally all platforms should match the original Java runtime semantics.

**Comment by frett** [comment]
I'm good with my contributions being released under BSD-3

**Comment by wilkomanger** [comment]
Hi, I was mentioned but I've only opened issues, don't you think you need my approval!

**Comment by ftomassetti** [comment]
> Hi, I was mentioned but I've only opened issues, don't you think you need my approval!

wilkomanger, you have actually contributed a commit a few years ago, so yes, we need your approval

**Comment by wilkomanger** [comment]
Ah sorry, weird, couldn't find it before. Then yes I give permission 👍

**Comment by ftomassetti** [comment]
Ok, also Tim granted us permissions to do the change. We are missing a single contributor (Brian). I will try to ping him and see if we can get permissions also from him.

I never thought we could reach this point so quickly. Thank you to all of you for your prompt support!

**Comment by brianguertin** [comment]
Also OK from me to license any contributions I've made under BSD-3.

**Comment by ftomassetti** [comment]
Thank you all!
This was a chance to get in chance with all of you and thank you for your contributions.

I opened a PR to specify that the code is now available also under BSD: #147

**Comment by ftomassetti** [comment]
Change to the licensing model done. Thank you once more!

**Comment by ftomassetti** [comment]
As a follow-up: thanks to your help the code you provided has now been included in [ANTLR5](https://github.com/antlr/antlr5). The merge has been done in a way to preserve the git history. This meant a lot of work for the person who did it, but it also means that all of you now appear among the [contributors to ANTLR5](https://github.com/antlr/antlr5/graphs/contributors).

Development of ANTLR Kotlin will continue for years to come, until ANTLR5 is fully stable and users have migrated to it.
