### ISSUE TITLE
Token "name" conflicts with enum name

### ISSUE THREAD

**Issue by piacenti** [Strumenta/antlr-kotlin#145]
I updated to the latest version and noticed that if I have a parser rule "name" in my grammar it generates an enum entry of "name" which conflicts with the enum "name" field. Previously it would prefix all rule enum entries with "RULE_" which is verbose but prevents name clashes.

**Comment by lppedd** [comment]
Checking! Thanks for the report.

**Comment by lppedd** [comment]
Would it be ok if we capitalize enum names?
E.g., from:

```kotlin
public enum class Rules(public val id: kotlin.Int) {
    `line`(1),
    `name`(2),
    `print`(3),
}

```
to:

```kotlin
public enum class Rules(public val id: kotlin.Int) {
    `Line`(1),
    `Name`(2),
    `Print`(3),
}
```

**Comment by piacenti** [comment]
yeah I think capitalizing makes sense. It is similar to how tokens function while easily distinguishable in code and shouldn't ever have a conflict with language level functionality.

**Comment by piacenti** [comment]
This should also address "id" which just happened to be another conflict (with constructor id) found in another one of my grammars' parse rules

**Comment by lppedd** [comment]
I'm trying a different way, without using enums.

Regarding your last comment, do you have an example snippet?

**Comment by piacenti** [comment]
![image](https://github.com/Strumenta/antlr-kotlin/assets/7397483/b0b7626c-9c8b-4ddc-a2de-d0dd76551881)

**Comment by lppedd** [comment]
Ahhhh got it now! Thanks!

**Comment by lppedd** [comment]
I will replace enums with object-s acting as namespaces.

They will contain const values, which will resolve both issues and also provide a performance boost, since values are inlined at compile time.
