### ISSUE TITLE
Update license descriptions also in POMs and headers

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/antlr-kotlin#148]
As a follow up of #144 we should update the license description also in:
* POMs (see buildSrc/src/main/kotlin/com/strumenta/antlrkotlin/gradle/ext/MavenPublishBaseExtension.ext.kt)
* The runtime sources (see antlr-kotlin-runtime/src/jsAndWasmSharedMain/kotlin/com/strumenta/antlrkotlin/runtime/WeakHashMap.kt, for example)

**Comment by lppedd** [comment]
@ftomassetti for the runtime sources, we can use a very simple message, like [this](https://github.com/JetBrains/intellij-community/blob/8f9509d21c4b2017aa888a6c78501879b820a722/platform/core-api/src/com/intellij/psi/PsiElement.java#L1).

It's not required to re-write the entire license(s) for every source file.

**Comment by ftomassetti** [comment]
> @ftomassetti for the runtime sources, we can use a very simple message, like [this](https://github.com/JetBrains/intellij-community/blob/8f9509d21c4b2017aa888a6c78501879b820a722/platform/core-api/src/com/intellij/psi/PsiElement.java#L1).

Agreed
