### ISSUE TITLE
Predicate For Parser Rule Ignores Nullability

### ISSUE THREAD

**Issue by piacenti** [Strumenta/antlr-kotlin#157]
I have a rule with multiple paths guarded by predicates and it generates this:
![image](https://github.com/Strumenta/antlr-kotlin/assets/7397483/86c8323d-976b-42d7-82f3-7286f1f40f7f)

The rule predicate is using standard format `{$rtype in listOf("...")}?`

This is not a problem for scenarios not ending on the when blocks in the sempred methods.

This is happening for both versions 0.1.1 and 0.1.2 which is the latest

**Comment by lppedd** [comment]
Looking into it.
