### ISSUE TITLE
JsName Only Available in Common and JS Projects

### ISSUE THREAD

**Issue by piacenti** [Strumenta/antlr-kotlin#175]
I know you just added JsName to solve for label variable name clashes. However, when not using a JS target the import for that is taken as an error. I'm not sure if there is an easy fix but for now I'm just running a gradle task to delete all JsName references for jvm only projects.
My use case is needing to use an antlr grammar in gradle buildSrc to do some automation for the build process. Gradle buildSrc is generally just a jvm project.

![image](https://github.com/Strumenta/antlr-kotlin/assets/7397483/3c22c65e-36ac-480b-857d-e874947c2c39)

**Comment by lppedd** [comment]
Not an easy one. Let me see if it's doable.

**Comment by ftomassetti** [comment]
This problem seems weird to me. How is it possible that the JetBrains team did not consider this use case?

**Comment by lppedd** [comment]
@ftomassetti the thing is it doesn't depend on the binaries we ship, but it depends on the code we generate.

The `kotlin-jvm` plugin doesn't contain JS related definitions, that's why `JsName` is not found. If you think about it from this perspective, it makes more sense.

**Comment by lppedd** [comment]
@piacenti RC2 is out, so you can remove your workaround.
