### ISSUE TITLE
Dependency not found for the Gradle plugin

### ISSUE THREAD

**Issue by softwarehangar7** [Strumenta/antlr-kotlin#20]
Ciao Federico,

I tried to use the Gradle plugin it seems that it cannot find a dependency on antlr-kotlin-target.

Should I add another repository URL to satisfy this?

Regards,

Luigi

**Comment by ftomassetti** [comment]
@unosviluppatore is working on getting this fixed. Sorry for the late answer

**Comment by drieks** [comment]
@softwarehangar7 can you add the gradle file that you have used? Please also have a look at https://github.com/Strumenta/antlr-kotlin/blob/master/antlr-kotlin-examples-jvm/build.gradle.kts, maybe it is already fixed in the new version 0.0.5.

**Comment by MiSawa** [comment]
Thank you for this great project!
I googled `antlr multiplatform` without expecting the existence, but here it is!!!

Though, I also found that I can't resolve dependencies using jitpack.
More specifically, I tried to use `2e25fd5`, but it seems to me that there is a problem on [the module file of that version](https://jitpack.io/com/strumenta/antlr-kotlin/antlr-kotlin-gradle-plugin/2e25fd550f/antlr-kotlin-gradle-plugin-2e25fd550f.module), where it points the version and the URL including `0.0.5` which doesn't exist in jitpack.
I tried dependency substitution to substitute `0.0.5` into `2e25fd5` as well, but it didn't affect the URL of artifacts.

I eventually found that the following works, but it's not elegant.
<details><summary>open fold</summary>

```kotlin
classpath("com.strumenta.antlr-kotlin:antlr-kotlin-target:$antlrKotlinVersion") {
    artifact {
        name = this@classpath.name
        extension = "jar"
        type = "jar"
        url = "https://jitpack.io/com/strumenta/antlr-kotlin/${this@classpath.name}/$antlrKotlinVersion/${this@classpath.name}-$antlrKotlinVersion.jar"
    }
}
classpath("com.strumenta.antlr-kotlin:antlr-kotlin-gradle-plugin:$antlrKotlinVersion") {
    exclude(group = "com.strumenta.antlr-kotlin", module = "antlr-kotlin-target")
    artifact {
        name = this@classpath.name
        extension = "jar"
        type = "jar"
        url = "https://jitpack.io/com/strumenta/antlr-kotlin/${this@classpath.name}/$antlrKotlinVersion/${this@classpath.name}-$antlrKotlinVersion.jar"
    }
}
// and we need more for the runtime dependencies
```
</details>

Do you have any idea if there is a better way?

**Comment by ftomassetti** [comment]
Now the project is published on Maven Central, and therefore it should be easier to get the dependency.
Sorry that it took a while
