### ISSUE TITLE
Update to ANTLRv4 4.7.2

### ISSUE THREAD

**Issue by drieks** [Strumenta/antlr-kotlin#26]
I'm not working on this, but we should prevent duplicate work, so I'm just mention it here for now.

**Comment by ftomassetti** [comment]
Hi, any progress on this one?

**Comment by drieks** [comment]
Hi, I have currently no time to work on the update..

**Comment by lppedd** [comment]
@ftomassetti same as the other two.

**Comment by ftomassetti** [comment]
Solved, as we now support ANTLR 4.13
