### ISSUE TITLE
Type inference failed

### ISSUE THREAD

**Issue by drieks** [Strumenta/antlr-kotlin#27]
I'm getting this error:

```
Type inference failed: Not enough information to infer parameter T in inline fun <T> listOf(): List<T>
Please specify it explicitly.
```
This is the code:
```
private val LITERAL_NAMES = listOf()
```

Old Version:
```
private val LITERAL_NAMES = Arrays.asList<String?>()
```

Fixed Version:
```
private val LITERAL_NAMES: List<String?> = listOf()
```

(https://github.com/kotlinx/ast/blob/9cddef2587f0c2702c557d004c7d5ef5a520ff38/kotlin/src/commonAntlr/kotlin/kotlinx/ast/kotlin/generated/UnicodeClasses.kt#L31)

**Comment by ftomassetti** [comment]
Not sure why this was closed. Was that fixed in a PR?

**Comment by drieks** [comment]
Hi @ftomassetti,

this Issue was automaticly closed by commit https://github.com/Strumenta/antlr-kotlin/commit/cf6564c0f3d6a3754784cd392e9de37b06d5c0ae, part of https://github.com/Strumenta/antlr-kotlin/pull/25

I just added the issue to document it and why I changed the code.
