### ISSUE TITLE
fix this please : var instead of val, cast not needed ?

### ISSUE THREAD

**Issue by Lakedaemon** [Strumenta/antlr-kotlin#36]
In Kotlin.stg...

Could you have a look if it would be possible to remove this cast
_localctx as <f.ctxType>
(it gives me a lot of uneeded cast warning in intellij idea)

and maybee could you have alook if you should use a var instead a val in 
AttributeDecl(d) ::= "val <d.name> <if(d.type)>: <d.type><endif><if(d.initValue)> = <d.initValue><endif>"
with some initialization (like var ....:String="") or lateinit var...

Also, maybee it is necessary to prevent the use of types like Int, String, ...
in enums
maybee in kotlinKeywords in KotlinTarget.java?

**Comment by ftomassetti** [comment]
Bonjour Olivier,
I think these are three separate issues, ideally they should live in three separate tickets.

**Point 1**
> Could you have a look if it would be possible to remove this cast
_localctx as <f.ctxType>
(it gives me a lot of uneeded cast warning in intellij idea)

Yes, we can do that. In general you should not look at generated files and you should exclude them from the files analyzed for warnings

**Point 2**

> and maybee could you have alook if you should use a var instead a val in
AttributeDecl(d) ::= "val <d.name> <if(d.type)>: <d.type><if(d.initValue)> = <d.initValue>"
with some initialization (like var ....:String="") or lateinit var...

Why is that?

**Point 3**

> Also, maybee it is necessary to prevent the use of types like Int, String, ...
in enums
maybee in kotlinKeywords in KotlinTarget.java?

This makes sense

>

**Comment by Lakedaemon** [comment]
About point 2 :

The generated code has a lot of stuff like 
`(_localctx` as C0Context).op = "cph";

but _localctx has been created with stuff like 
`var _localctx : CC2Context = CC2Context(context, state)

except that with have val op : String in the definition of CC2Context

`open class CC2Context : ParserRuleContext {
`	    override var ruleIndex: Int
`	        get() = Rules.RULE_cC2.id
`	        set(value) { throw RuntimeException() }
`		val op : String

So, the generated code cannot compile... :/
now, when I replaced val op : String with var op : String ="",
everything compiled just fine :)

If I do a clean, it gets regenerated though and I had to redo it to build my project
(so I ended up copying my modified generated parser and I switched off the generation of kotlin-antler code in my build :/)

**Comment by ftomassetti** [comment]
Hi Olivier, regarding point 1, the cast is needed and removing it cause the build to fail.
In general you should configure your IDE so that it does not report warning on generated code, however we can look for annotation to suppress the unnecessary cast.

**Comment by ftomassetti** [comment]
Unnecessary cast do not give a warning to me and I could not find a way to remove them

**Comment by Lakedaemon** [comment]
I see. Thanks for the feedback. Maybee my parser doesn't need casts but others might.
I was mistaken. Many thanks for your work on kotlin-antlr and on kotlin-multi-targets goals :)

**Comment by Lakedaemon** [comment]
Regarding point 2
I am writing another parser and whenever I use stuff like "locals", 
`dummy_binder locals[String variant] : '{' dummy_Identifier* ':' type '}' {$variant="{"} |
`                '(' dummy_Identifier* ':' type ')' {$variant="("};`

I have the exact same issue (a val is generated instead of a var) and then compilation fails because of stuff like
` open class Dummy_binderContext : ParserRuleContext {
`		val variant : String
`
` var _localctx : Dummy_binderContext = Dummy_binderContext(context, state)
<<  here the ide says that the var can be a val
` 
` _localctx.variant="{"
<< compilation fails : val cannot be reassigned

I can workaround this by changing my grammar (but it becomes less simple/readable),
with some grammar/antlr/parser magic I'll be able to differentiate cases with '()' and cases qith '{}'

Or I can manually change val into var

**Comment by dooxe** [comment]
Hey, do you have any news about this issue ? 
I'm facing it right now : grammar variables identifiers are defined like Kotlin `val` in the generated code, and make them not assignable to compute the result.

**Comment by ftomassetti** [comment]
A PR for this would be appreciated

**Comment by lppedd** [comment]
This has been solved in 8099787a60344a0a13007b0314d72d06a29bcfd0 AFAIU.  
@ftomassetti you could close this one to not mislead users.

**Comment by ftomassetti** [comment]
Thank you @lppedd , I am doing that
