### ISSUE TITLE
Add Kotlin/native support

### ISSUE THREAD

**Issue by brianguertin** [Strumenta/antlr-kotlin#40]
I'm interested in using a simple antlr grammer in a cross-platform project (Android/iOS/Desktop) and it sounds like adding Kotlin/Native support to this project might be straightforward, given that it's already structured for multi-platform.

IMO, this would be a killer feature for this library. Upstream antlr already includes targets for JVM, JS (the ones this library also supports). But, there is no antlr C target, which makes using antlr from Kotlin/native difficult (as we can't interface directly with C++ version).

I may give this a shot myself if I have time in the coming weeks to contribute back to this project, so if you have any tips, that would be much appreciated.

I'm guessing all we need is the `actual` declarations in `antlr-kotlin-runtime` and adding a new example for native, doesn't sound too hard :)

**Comment by ftomassetti** [comment]
Hi Brian,
yes, it would be amazing to get Kotlin/Native support :)
I am all in favor to having it built

**Comment by brianguertin** [comment]
So, I built out the the native target to the point of compiling: https://github.com/brianguertin/antlr-kotlin/commit/afff41156b29fccd36b46810c2b26e90ec7618bb

However, There are several mutable global variables in use both in the ANTLR runtime and in the existing tests. Kotlin/native freezes all the global variables, which causes some trouble.

As a hack, If I comment out some of the globals or move them to class members, I am able to get 20/30 of the unit tests to pass on native. The rest still fail with InvalidMutabilityException.

I tried going further and fixing the global mutable fields in the MiniCalc test classes, but then those tests hang indefinitely instead of failing.

**Comment by brianguertin** [comment]
Here's where I left off on trying to fix the InvalidMutabilityException's in the tests, currently stuck on the hanging that I mentioned earlier. https://github.com/brianguertin/antlr-kotlin/commit/db1c34d7914b98031b10e1dd3073485df24c8454

**Comment by brianguertin** [comment]
For reference, here's the list of changes I needed to get the native target working:
- Added "native" target (with host OS detection for linux/mac/win) to build.gradle
- Copy jvmMain to nativeMain and fix compiler errors
- Add an expect/actual declaration for `synchronized`, which blocks native compilation (left it in for JVM, implemented as no-op on native & JS)
- Run `./gradlew nativeTest`, observe that some tests hang, some fail with InvalidMutabilityException
- Refactor/remove mutable global state (mutable data in companion objects is not allowed in Kotlin/native), managed to get as many as 20/30 of the tests passing, others still hang

**Comment by brianguertin** [comment]
Actually, managed to get everything passing, please see the PR :) https://github.com/Strumenta/antlr-kotlin/pull/41
