### ISSUE TITLE
Publish iOS & OS X targets

### ISSUE THREAD

**Issue by brianguertin** [Strumenta/antlr-kotlin#47]
Right now the README says to use Jitpack, but as far as I can tell jitpack only builds on Linux. This means even though the runtime works on iOS, OS X, and Windows, the `antlr-kotlin-runtime` cannot be used as a gradle dependency in those projects. Instead it requires manually building the package on each target platform.

If we set up CI to run on a mac host (supported by travis CI), it could build all targets (including Windows via wine, but I would not make that a priority).
https://github.com/JetBrains/kotlin-native/blob/master/RELEASE_NOTES.md
https://docs.travis-ci.com/user/reference/osx/

The build.gradle also needs to be updated add the iOS platform, and to enable cross-compiling if the platform supports it (Building once on OS X will be easier than building on 2 or 3 different VMs)

**Comment by brianguertin** [comment]
I plan work on the `build.gradle` changes in the coming week :)

I guess CI could be set up independently of that. Or, we could skip CI and whoever has jcenter access could just republish once I've updated the build.gradle to include all the targets

**Comment by brianguertin** [comment]
Kotlin 1.4. might make this easier, eventually: https://blog.jetbrains.com/kotlin/2019/12/what-to-expect-in-kotlin-1-4-and-beyond/

"Kotlin/Native has been using the KLibs format to distribute Kotlin native libraries for quite a while, and now we are extending the format to support other back-ends and multiplatform libraries. The format will be experimental in 1.4, and we will work on providing a stable ABI for it in future versions."

**Comment by svihar** [comment]
Hi, any plans to work on this issue? I am getting:

> Could not find com.strumenta.antlr-kotlin:antlr-kotlin-runtime-mac:b5135079b8.
