### ISSUE TITLE
Open up methods and classes

### ISSUE THREAD

**Issue by piacenti** [Strumenta/antlr-kotlin#50]
ANTLR was designed with extensibility through subclassing in mind. There are currently some limitations where we can't subclass or override methods. One such example is if you want to disable recovery on a Lexer (currently the recover method is not open). Might be worth using the kotlin-allopen plugin to help with some of that.

**Comment by ftomassetti** [comment]
Thank you for opening the issue. This code has been created as a direct translation from the Java codebase, so we inherited the same approach here. I agree it could make sense to increase openness and I would be happy to consider PRs for that

**Comment by lppedd** [comment]
Most classes and methods/properties have been opened.  
I think this can be closed in favor of more specific issues.

**Comment by ftomassetti** [comment]
Agreed
