### ISSUE TITLE
wrong non-null assumption on unrollRecursionContexts()

### ISSUE THREAD

**Issue by atsushieno** [Strumenta/antlr-kotlin#60]
I have some syntax that causes run-time crash, saying:

> java.lang.NullPointerException: null cannot be cast to non-null type org.antlr.v4.kotlinruntime.ParserRuleContext

![image](https://user-images.githubusercontent.com/53929/111060121-01a30880-84de-11eb-8193-a0a3e8c6e779.png)

(stacktrack omitted as they mostly mention my code.)

My syntax defines left-recursion like `A : B | A B` which I assume is the cause of the problem.

Here is the mentioned suspect in the trace:

https://github.com/Strumenta/antlr-kotlin/blob/0951069063d9bbe249eebb981925217a12f55f14/antlr-kotlin-runtime/src/commonMain/kotlin/org/antlr/v4/kotlinruntime/Parser.kt#L722

It assumes that `context!!.readParent()` returns non-null parent, but it actually returns null for my syntax, because the left recursion occurs at top level. Here is the screenshot on diagnosing that state:

![image](https://user-images.githubusercontent.com/53929/111060056-96593680-84dd-11eb-88dd-c5e2464d1387.png)

Confirmed with 0951069 on Ubuntu 20.04, multiplatform (jvm at runtime)

I'm creating a one liner PR that fixes this issue that makes it not crash.

**Comment by frett** [comment]
I'm running into this error as well, any chance the PR can get reviewed and merged?

**Comment by ftomassetti** [comment]
The PR has been merged. Sorry for the delay
