### ISSUE TITLE
How to use version 0.0.7 in gradle ? 

### ISSUE THREAD

**Issue by dooxe** [Strumenta/antlr-kotlin#66]
Hello,

I'm trying to configure my multiplatform project with gradle and antlr-kotlin, but I'm facing an issue with the classpath.
The template I use is the one on repo, i.e., [https://github.com/Strumenta/antlr-kotlin/blob/master/antlr-kotlin-examples-mpp/build.gradle.kts](https://github.com/Strumenta/antlr-kotlin/blob/master/antlr-kotlin-examples-mpp/build.gradle.kts).
The version of `antlr-kotlin` in the `gradle.properties` is `0.0.7`, but when I use it in gradle, the dependency is not found.
My `build.gradle.kts` is like the following : 
```
repositories {
    mavenCentral()
    jcenter()
    maven("https://jitpack.io")
}
buildscript {
    dependencies {
        val antlrKotlinVersion: String by project
        classpath("com.strumenta.antlr-kotlin:antlr-kotlin-gradle-plugin:$antlrKotlinVersion")
    }
}
```

The error I get is the following : 
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.strumenta.antlr-kotlin:antlr-kotlin-gradle-plugin:0.0.7.
Searched in the following locations:
  - https://plugins.gradle.org/m2/com/strumenta/antlr-kotlin/antlr-kotlin-gradle-plugin/0.0.7/antlr-kotlin-gradle-plugin-0.0.7.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
```

I'm having this error even with the Jitpack configuration.

How can I use the version `0.0.7` of `antlr-kotlin` with gradle (version `6.7`) ? 

Thanks a lot

**Comment by ftomassetti** [comment]
Currently the project is distributed through jitpack, so you should configure your project to get the plugin from there, not from the Gradle plugins repository. If you have problem configuring jitpack we can look into publishing the plugin to the gradle plugins portal

**Comment by dooxe** [comment]
I see. Is there a tutorial I can follow or a template I can use to configure my project to get the plugin from jitpack ?

**Comment by ftomassetti** [comment]
Hi @dooxe I double checked. For now the gradle plugin contains a task but not a proper plugin class. For this reason you can add it to the buildscript classpath and use the task to generate the Kotlin code. An example is available here: https://github.com/Strumenta/antlr-kotlin/blob/master/antlr-kotlin-examples-jvm/build.gradle.kts

In particular you should be interested in these lines:
```
buildscript {
    ...
    dependencies {
        // add the plugin to the classpath
        classpath("$groupProperty:antlr-kotlin-gradle-plugin:$antlrKotlinVersion")
    }
 }
 ```
 
Does this help?

We should also release this as a proper gradle plugin to simplify using it

**Comment by dooxe** [comment]
Hi @ftomassetti , sadly I have no more luck with this configuration.

The only version that is found by gradle is the `0.0.4`, all other versions found at https://jitpack.io/#com.strumenta/antlr-kotlin are not found.

Also, when building with the version `0.0.4`, I get the following error:
```
Cannot assign to 'antlrClasspath': the setter is protected/*protected and package*/ for synthetic extension in '<dependencies of buildscript>'
```

Thanks a lot for your help!

**Comment by ftomassetti** [comment]
> Hi @ftomassetti , sadly I have no more luck with this configuration.
> 
> The only version that is found by gradle is the `0.0.4`, all other versions found at https://jitpack.io/#com.strumenta/antlr-kotlin are not found.

Did you had the jitpack repository?
Did you look into this? https://jitpack.io/

> 
> Also, when building with the version `0.0.4`, I get the following error:
> 
> ```
> Cannot assign to 'antlrClasspath': the setter is protected/*protected and package*/ for synthetic extension in '<dependencies of buildscript>'
> ```
> 
> Thanks a lot for your help!

**Comment by dooxe** [comment]
Hi @ftomassetti,

I have found out something interesting : for my build to work, I need to put the `repositories` gradle closure **inside** `buildscript` like that:

build.gradle.kts
```kts
...
buildscript {
    repositories {
        mavenCentral()
        maven(url="https://jitpack.io")
    }
    val antlrKotlinGroupProperty = "com.strumenta.antlr-kotlin"
    val antlrKotlinVersion : String by project
    dependencies {
        classpath("$antlrKotlinGroupProperty:antlr-kotlin-gradle-plugin:$antlrKotlinVersion")
    }
}
...
```

Also, it is the same for the block to configure `commonAntlr` source sets and dependencies:
```kts
val commonAntlr by creating {
            ...
            repositories {
                //mavenLocal()
                mavenCentral()
                maven(url="https://jitpack.io")
            }
            ...
            dependencies {
                api(kotlin("stdlib-common"))
                val antlrKotlinGroupProperty = "com.strumenta.antlr-kotlin"
                val antlrKotlinVersion : String by project
                api("$antlrKotlinGroupProperty:antlr-kotlin-runtime-jvm:$antlrKotlinVersion")
            }
            kotlin.srcDir("build/generated-src/commonAntlr/kotlin")
        }
```

Then, when I specify a Jitpack release version ... it works! I finally manage to generate kotlin files from my ANTLR .g4 files. 
It's good to sleep on it sometimes! 

Thanks a lot for your help!

**Comment by DRSchlaubi** [comment]
> Currently the project is distributed through jitpack, so you should configure your project to get the plugin from there, not from the Gradle plugins repository. If you have problem configuring jitpack we can look into publishing the plugin to the gradle plugins portal

The problem with jitpack is that it is really stupid.

It doesn't detect this project as a multimodule one in the UI and it also doesn't ifn the kotlin-target module

**Comment by hakanai** [comment]
The tidiest way I found to get this to work:

In `build.gradle.kts`:

```kotlin
plugins {
    id("com.strumenta.antlr-kotlin") version "ebf3caf7ff" apply false
}
```

Notes:
1. The `apply false` here works around the plugin not really containing a plugin.
2. I would prefer to use a real version number, but there doesn't appear to be one published?
3. If you do just this, it still won't work, because the plugin metadata isn't published correctly, which may also be a jitpack quirk. So there's this second part of the workaround below.
4. Observe how much tidier this is than what's in `build.gradle.kts` in the example projects in this repo.

The ugly stuff is all constrained to `settings.gradle.kts`:

```kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        // antlr-kotlin currently not publishing on plugin portal :(
        // https://github.com/Strumenta/antlr-kotlin/issues/66
        maven("https://jitpack.io") {
            content {
                includeGroup("com.strumenta.antlr-kotlin")
            }
        }
    }

    resolutionStrategy {
        eachPlugin {
            // antlr-kotlin apparently not published with proper plugin metadata, so forcing the right module
            if (requested.id.id == "com.strumenta.antlr-kotlin") {
                useModule("com.strumenta.antlr-kotlin:antlr-kotlin-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

Notes:
1. The `content {}` block is insurance against accidentally using jitpack if some other module disappears from the plugin portal in the future. If that happened and it got fetched from jitpack instead, I can't guarantee that whatever jitpack built would be identical.
2. Using `eachPlugin {}` to map a group:artifact for a plugin ID is a nice trick if you are like me and absolutely refuse to do things the outdated way. It's what lets us use the `plugins {}` block in the normal way regardless of how the plugin has been published.

**Comment by ftomassetti** [comment]
Availability on Maven Central should solve this one
