### ISSUE TITLE
how do you set up a kotlin multiplatform project with this ?

### ISSUE THREAD

**Issue by Lakedaemon** [Strumenta/antlr-kotlin#7]
I have tried adapting the gradle file of the ReadMe without success.
compileKotlin isn't found maybee because I use 
apply plugin: 'kotlin-platform-common'

My last try with gradle.build 

buildscript {
    ext.kotlin_version = '1.3.11' //'1.3.0-rc-57'//2.30'
    ext.antlrKotlinVersion = "b28896341f" // see notes on jitpack version

    repositories {
        maven { url "http://dl.bintray.com/kotlin/kotlin-eap"}
        mavenCentral()
        mavenLocal()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.strumenta.antlr-kotlin:antlr-kotlin-gradle-plugin:${antlrKotlinVersion}"
    }
}

apply plugin: 'kotlin-platform-common'
apply plugin: 'idea'
apply plugin: 'com.strumenta.antlrkotlin'

repositories {
    maven { url "http://dl.bintray.com/kotlin/kotlin-eap"}
    mavenCentral()
    mavenLocal()
    jcenter()
    maven { url "https://jitpack.io" }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
        languageVersion = "1.3"
    }
}

dependencies {
    compile "com.strumenta.antlr-kotlin:antlr-kotlin-runtime-common:${antlrKotlinVersion}"
    compile "com.strumenta.antlr-kotlin:antlr-kotlin-runtime-jvm:${antlrKotlinVersion}"
    
    
    compile "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version"

    compile group: 'org.apache.tinkerpop', name: 'gremlin-core', version: '3.3.0'
    compile 'com.github.pardom:redux-kotlin:1.2.0'
    compile 'com.github.jvm-redux.jvm-redux-api:api:1.2.0'

    testCompile "org.jetbrains.kotlin:kotlin-test-annotations-common:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-common:$kotlin_version"

}

def genFolder = new File( projectDir.path + '/generated-src/antlr/' )

generateKotlinGrammarSource {
    maxHeapSize = "64m"
    arguments += ['-package', 'com.strumenta.financialdsl']
    outputDirectory = new File( genFolder.toString())
}
org.jetbrains.kotlin.gradle.tasks.KotlinCompile.dependsOn(generateKotlinGrammarSource)

sourceSets {
    generated {
        kotlin.srcDir genFolder
    }
}
//compileKotlin.source sourceSets.generated.kotlin, sourceSets.main.kotlin

/*clean{
    delete fileTree(dir: genFolder , include: '*.kt')
    delete fileTree(dir: genFolder , include: '*.interp')
    delete fileTree(dir: genFolder , include: '*.tokens')
}*/

idea {
    module {
        sourceDirs += genFolder
    }
}

/*compileKotlin {
    kotlinOptions {
        languageVersion = "1.3"
    }
}*/

**Comment by nr23730** [comment]
> I also tried seting up antlr4.7.2 and using this on the command line
> java -classpath /usr/local/lib/ -jar /usr/local/lib/antlr-4.7.2-complete.jar -Dlanguage=Kotlin -o /home/lakedaemon/IdeaProjects/mephistolus/src/commonMain/kotlin -visitor -no-listener /home/lakedaemon/IdeaProjects/mephistolus/src/commonMain/kotlin/Math.g4
> 
> I had this file in the . directory (/usr/local/lib) : antlr-kotlin-target-b28896341f.jar
> 
> I still got error(31): ANTLR cannot generate Kotlin code as of version 4.7.2

The official ANTLR-complete packages do not contain support for Kotlin. You have to use the "antlr-kotlin-target". The easiest way is to compile these components and add them to your classpath. But you can also build ANTLR including these files.

**Comment by Lakedaemon** [comment]
Well, compilation fails (with gradle build/assemble) with this outpuut (I tried to build the zip I downloaded from here)

:antlr-kotlin-gradle-plugin:compileJava/home/lakedaemon/IdeaProjects/antlr-kotlin-master/antlr-kotlin-gradle-plugin/src/main/java/com/strumenta/antlrkotlin/gradleplugin/AntlrKotlinTask.java:255: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/lakedaemon/IdeaProjects/antlr-kotlin-master/antlr-kotlin-gradle-plugin/src/main/java/com/strumenta/antlrkotlin/gradleplugin/internal/AntlrSourceVirtualDirectoryImpl.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/lakedaemon/IdeaProjects/antlr-kotlin-master/antlr-kotlin-gradle-plugin/src/main/java/com/strumenta/antlrkotlin/gradleplugin/AntlrKotlinPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

**Comment by Lakedaemon** [comment]
I can also get some jitpack jars, but what do I do with them afterwards ? May I use those with the binary antlr 4.7.2 if I somehow manage to include them in the jar classpath (what files sjould I use) ?

**Comment by Lakedaemon** [comment]
The kotlin multiplatform model changed lately, with the kotlin 1.3 release.
Maybee, this is why I did not manage to make it work

**Comment by ftomassetti** [comment]
Hi, sorry for the late reply. Yes, I should probably update it to Kotlin 1.3. 
Of course help with this would be welcome :)

**Comment by Lakedaemon** [comment]
I wish I could help you. :/
Sadly, I can only test and report bugs/issues. 
I know nothing about gradle plugins and compiling antlr.

**Comment by phyrian** [comment]
@ftomassetti  I created a pull request, the lib here is updated to Kotlin 1.3 and works for Kotlin Multiplatform projects.
https://github.com/Strumenta/antlr-kotlin/pull/23

**Comment by drieks** [comment]
I also added an mpp example in #25

**Comment by drieks** [comment]
@ftomassetti: I think this issue can be closed now.
