### ISSUE TITLE
Support Antlr 4.9.2

### ISSUE THREAD

**Issue by Alexstoppel** [Strumenta/antlr-kotlin#70]
Hey, 

it would be great if antlr-kotlin would support Antlr 4.9.2 to solve issues like [Maximum call stack size exceeded](https://stackoverflow.com/questions/66031981/using-javascript-grammar-in-antlr4-and-get-maximum-call-stack-size-exceeded-erro). 

Thanks in advance

**Comment by lppedd** [comment]
@ftomassetti I don't think this applies to the Kotlin runtime, but this can be closed anyway as we support 4.13.1 now.

**Comment by ftomassetti** [comment]
Solved, as we support ANTLR 4.13
