### ISSUE TITLE
Implement new caseInsensitive Options

### ISSUE THREAD

**Issue by piacenti** [Strumenta/antlr-kotlin#79]
For awareness https://github.com/antlr/antlr4/pull/3399 implemented a new option that would be worth supporting. I might create PR when I get time which may take a while. Creating this issue in case someone wants to go ahead on implementing this.

**Comment by ftomassetti** [comment]
Thank you for pointing this one out!

**Comment by lppedd** [comment]
This options are implemented on the ANTLR4 tool side. If it has it, this target supports it, so this can be closed.

**Comment by ftomassetti** [comment]
Closing as suggested
