### ISSUE TITLE
Generated properties for non-nullable children should not be declared nullable

### ISSUE THREAD

**Issue by hakanai** [Strumenta/antlr-kotlin#84]
For a rule like this:

```antlr
number: nested=(INTEGER | FLOAT | PI | INFINITY);
```

There is no way with that grammar that the nested token could be null, but the property you get after compiling the grammar is:

```kotlin
public final var nested: Token?
```

So now I have to put `!!` all over my code to assert something the grammar is already supposed to be doing for me.

The more insidious side of this issue is, I can't just put `!!` on _all_ of them, because _some_ of them really are nullable. And the nullability may change from time to time as the grammar evolves. So it would be nice if the generated code matched the actual grammar.

**Comment by lppedd** [comment]
Did you ever find a way to get this one solved?

**Comment by lppedd** [comment]
The real answer is this is not possible, as the engine that looks for template parts does not differentiate between nullable or non-nullable tokens.

You should open an issue upstream on the ANTLR4 repository, as other languages like Swift are affected.  
@ftomassetti imo even this one can be closed as we can't do anything.

**Comment by ftomassetti** [comment]
Agreed, let's close this one

**Comment by lppedd** [comment]
@ftomassetti can we reopen? Working in this.

**Comment by ftomassetti** [comment]
Sure, reopening
