### ISSUE TITLE
Charset used to compile the grammar is system default, not UTF-8

### ISSUE THREAD

**Issue by hakanai** [Strumenta/antlr-kotlin#85]
I was using the following configuration:

```kotlin
val generateKotlinGrammarSource by tasks.registering(AntlrKotlinTask::class) {
    antlrClasspath = configurations.detachedConfiguration(
        project.dependencies.create("com.strumenta.antlr-kotlin:antlr-kotlin-target:ebf3caf7ff")
    )

    source = project.objects
        .sourceDirectorySet("antlr", "antlr")
        .srcDir("src/main/antlr").apply {
            include("**/*.g4")
        }
    outputDirectory = file("$buildDir/generated-src/antlr/main/kotlin")
}
```

The grammar appeared to compile fine, but then rules using Unicode [inside my .g4 file](https://github.com/ephemeral-laboratories/red-rocket/blob/main/src/main/antlr/garden/ephemeral/rocket/util/RealExpression.g4#L44,L46) were not passing the tests.

It turned out I had to manually set the encoding:

```kotlin
val generateKotlinGrammarSource by tasks.registering(AntlrKotlinTask::class) {
    arguments = arguments + listOf("-encoding", "UTF-8")
    // ...
}
```

It's 2022; I think UTF-8 can be the default by now and we shouldn't be forcing every project to set this themselves.

**Comment by ftomassetti** [comment]
Yes, I think this makes sense. I understand it is inconvenient for users but I think it is not worth having a separate gradle plugin just for this. I think at best we can add an issue on the gradle plugin

**Comment by ftomassetti** [comment]
Our plugin should not use UTF-8 by default (thank you @lppedd for pointing that out)
