### ISSUE TITLE
Invalid imports in generated parser and lexer classes

### ISSUE THREAD

**Issue by NorbertSandor** [Strumenta/antlr-kotlin#9]
I use version `88ad3eff27`.

Compilation fails because both the parser and the lexer contains the invalid import:
`import org.antlr.v4.runtime.misc.Utils`
It works if the import is changed to:
`import org.antlr.v4.kotlinruntime.misc.Utils`

Compilation fails because the following import is missing in both the parser and the lexer classes:
`import com.strumenta.kotlinmultiplatform.toCharArray`

**Comment by ftomassetti** [comment]
Thank you for reporting this, I will fix it right away
