### ISSUE TITLE
SemanticContext AND/OR hashcode NotImplemented

### ISSUE THREAD

**Issue by mistralaix** [Strumenta/antlr-kotlin#93]
Hello, I am trying to use the library but I see that the function hashCode in the SemanticContext file for the class AND and OR are not implemented.

I tried to use the MurmurHash library but I couldn't make it work.

Let me know if you have suggestions regarding the implementation.

Thank you!

**Comment by lppedd** [comment]
@ftomassetti this one is done, can be closed.

**Comment by ftomassetti** [comment]
Closing it
